### ISSUE TITLE
pcf-colocate-firehose_exporter.yml missing logging url in 25.0

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [pivotal-cf/pcf-prometheus-pipeline#33]
In pcf-colocate-firehose_exporter.yml the doppler url is part of the `doppler` element. In v25 of the bosh release they moved it to an element called `logging`

### doppler element
https://bosh.io/jobs/firehose_exporter?source=github.com/cloudfoundry-community/prometheus-boshrelease&version=25.0.0#p%3dfirehose_exporter.doppler

### logging element 
https://bosh.io/jobs/firehose_exporter?source=github.com/cloudfoundry-community/prometheus-boshrelease&version=25.0.0#p%3dfirehose_exporter.logging

### possible replacement
Here is a sample where the url was moved to logging and the use_legacy_firehose property is set. This is similar to how these  nodes are structured in the example manifest:
https://github.com/bosh-prometheus/prometheus-boshrelease/blob/fe5c56b82ec68d947d81dd8e39a76a83c34a03d1/manifests/operators/monitor-cf.yml#L40

```
- type: replace
  path: /instance_groups/name=prometheus2/jobs/-
  value:
    name: firehose_exporter
    release: prometheus
    properties:
      firehose_exporter:
        doppler:
          subscription_id: "((metrics_environment))"
          max_retry_count: 300
        logging:
          url: wss://doppler.((system_domain)):((traffic_controller_external_port))|
          use_legacy_firehose: true
        uaa:
          url: https://uaa.((system_domain))
          client_id: firehose_exporter
          client_secret: "((uaa_clients_firehose_exporter_secret))"
        metrics:
          environment: "((metrics_environment))"
        skip_ssl_verify: ((skip_ssl_verify))
```
